### PR TITLE
arrays_baris_zirhli.py

### PR DESCRIPTION
**Pull request by BarisZirhli**

### CODE REVIEW

**Review by canbula — CHANGES_REQUESTED** [review]
You can't use NumPy without import it, right?

**Comment by BarisZirhli** [comment]
> You can't use NumPy without import it, right?

> Sorry about that,exactly I can not manipulated without using the Numpy I will fix ASAP and review once more time Thanks for patience and supporting

**Review by canbula — CHANGES_REQUESTED** [review]
It is `numpy`, not `Numpy`. Barış, do not open any pull request unless you run the code on your computer.

**Review by canbula — CHANGES_REQUESTED** [review]
Check the tests, you have failed some of them. The problem is the way you are using to raise the error.

**Comment by BarisZirhli** [comment]
> Check the tests, you have failed some of them. The problem is the way you are using to raise the error.

I can not find out failure reason, even if I tried other who upload guys codes but result did not change.
failed cases force to show up wrong values in parameter. My exception handle lines, respond related answer to them. 
What should I have been expected as output? I have no idea but, I know that if someone put (2,5,13) test codes will not allow pass.

**Review by canbula — CHANGES_REQUESTED** [review]
❓

**Pull request closed without merging**
