### PR TITLE
Week04 homework added Bedirhan elçin

### PR DESCRIPTION
**Pull request by BedirhanE**

### CODE REVIEW

**Review by canbula — CHANGES_REQUESTED** [review]
Your code fails in some tests.

**Review by canbula — CHANGES_REQUESTED** [review]
You have failed in some tests of Week05. Check the results.

**Comment by BedirhanE** [comment]
I hope it passes all the tests now

**Review by canbula — CHANGES_REQUESTED** [review]
Bedirhan, the problem is the files you are uploading. You should only keep `Week04/arrays_bedirhan_elcin.py` and `Week05/bra_bedirhan_elcin.py`.
Screenshot 2023-11-07 at 13 02 41

**Review by canbula — CHANGES_REQUESTED** [review]
You still have the same problem Bedirhan, you are uploading all the files from your branch.

**Pull request closed without merging**
